openapi: '3.1.0'
info:
  title: ParksService
  version: 1.0.0
servers:
  - url: https://example.com/api
    description: Example service deployment.
paths:
  /parks:
    get:
      operationId: getParks
      responses:
        '200':
          description: A success response with parks.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Park'
components:
  schemas:
    Park:
      type: object
      properties:
        title:
          type: string
        rating:
          type: number
        icon:
          type: string
      required:
        - title
        - rating
        - icon
